SET SCHEMA FN71840@
--1 VIEW
CREATE VIEW ATTENDENTS_CLEAN_ROOMS_VIEW
AS 
	SELECT V2.ID_NUM, V2.NAMEE,V2.SALARY ,V1.R_NUMBER
	FROM MYROOMS V1, MYATTENDANTS V2
	WHERE  V2.ID_NUM = V1.ATTENDANT_ID AND V2.SALARY > 300@
--CALL 1 VIEW
SELECT * FROM ATTENDENTS_CLEAN_ROOMS_VIEW@

--2 VIEW
CREATE VIEW GUEST_STAY_VIEW
AS 
	SELECT V1.NAMEE, V1.EGN, V1.AGE_VAL, V2.R_NUMBER
	FROM MYGUESTS V1, MYREGISTRATIONS V2
	WHERE  V1.EGN = V2.GUEST_EGN @
	
--CALL 2 VIEW
SELECT* FROM GUEST_STAY_VIEW@	

--3 VIEW
CREATE VIEW MYREGISTRATIONS_INFO
AS
	SELECT *
	FROM MYREGISTRATIONS
	WHERE RECEPTIONIST_ID = 'REC101' AND GUEST_EGN = '8%'@
	
SELECT * FROM  MYREGISTRATIONS_INFO@


DROP VIEW FN71840.MYREGISTRATIONS_INFO@